---
- name: Get ARN for hosted cluster user
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "{{ ocp_workload_rhacm_hcp_s3_bucket_region }}"
  ansible.builtin.command:
    cmd: >-
      aws sts get-caller-identity --query "Arn"
  register: r_arn
  changed_when: false

- name: Debug r_arn
  ansible.builtin.debug:
    msg: "{{ r_arn.stdout }}"

- name: Create trust-relationship.json
  ansible.builtin.template:
    src: trust-relationship.json.j2
    dest: /tmp/trust-relationship.json
    mode: ug=rw,o=r

- name: Apply trust-relationship.json
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "{{ ocp_workload_rhacm_hcp_s3_bucket_region }}"
  ansible.builtin.command:
    chdir: /tmp
    cmd: >-
      aws iam create-role
        --role-name hcp-cli-role
        --assume-role-policy-document file://trust-relationship.json
        --query "Role.Arn"
  changed_when: true
  ignore_errors: true

- name: Get trust-relationship.json Arn
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "{{ ocp_workload_rhacm_hcp_s3_bucket_region }}"
  ansible.builtin.command:
    chdir: /tmp
    cmd: >-
      aws iam get-role
        --role-name hcp-cli-role
        --query "Role.Arn"
  register: r_role_arn
  changed_when: false
  ignore_errors: true

- name: Debug r_role_arn
  ansible.builtin.debug:
    msg: "{{ r_role_arn.stdout }}"

- name: Create awspolicy-hcp-cli-role.json
  ansible.builtin.template:
    src: awspolicy-hcp-cli-role.json.j2
    dest: /tmp/awspolicy-hcp-cli-role.json
    mode: "0664"

- name: Apply awspolicy-hcp-cli-role.json
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "{{ ocp_workload_rhacm_hcp_s3_bucket_region }}"
  ansible.builtin.command:
    chdir: /tmp
    cmd: >-
      aws iam put-role-policy
       --role-name hcp-cli-role
       --policy-name trust-relationship.json
       --policy-document file://awspolicy-hcp-cli-role.json
  changed_when: true
  ignore_errors: true

- name: Get STS credentials
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "{{ ocp_workload_rhacm_hcp_s3_bucket_region }}"
  ansible.builtin.shell:
    chdir: /tmp
    cmd: >-
      aws sts get-session-token --output json > sts-creds.json
  register: r_sts
  changed_when: true

- name: Read STS credentials file
  ansible.builtin.slurp:
    src: /tmp/sts-creds.json
  register: r_sts_creds

- name: Copy STS credentials to bastion
  delegate_to: "{{ (groups['bastions'] | default(['localhost']))[0] }}"
  ansible.builtin.copy:
    content: "{{ r_sts_creds.content | b64decode }}"
    dest: /tmp/sts-creds.json
    mode: ug=rw,o=r
